// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// // ignore: depend_on_referenced_packages
// import 'package:firebase_core/firebase_core.dart'
//  show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCmNv_bxlbJVy2GPENHkHkjD7KJKiQCxS8',
//     appId: '1:615380162521:web:0172c2060e388fc09c6bc8',
//     messagingSenderId: '615380162521',
//     projectId: 'fir-first-e6abd',
//     authDomain: 'fir-first-e6abd.firebaseapp.com',
//     storageBucket: 'fir-first-e6abd.appspot.com',
//     measurementId: 'G-VBPX4BJBJN',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBoTAKcffu_r_Vzq8L4lmU4Je_Jd2ZCFaM',
//     appId: '1:615380162521:android:fa957538b18e22219c6bc8',
//     messagingSenderId: '615380162521',
//     projectId: 'fir-first-e6abd',
//     storageBucket: 'fir-first-e6abd.appspot.com',
//   );
// }
